version: '3'
services:
  hinto_contract_microservice:
    build: .
    command: 'nodemon .'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
